---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: define php_packages
  set_fact: php_packages="{{ __php_packages | list }}"
  when: php_packages is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: copy php ini
  template:
    src: php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
  when: php_ini_use_template

- name: copy php opcache.ini
  template:
    src: opcache.ini.j2
    dest: /etc/php.d/10-opcache.ini
    owner: root
    group: root
  when: php_opcache_ini_use_template
