---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_packages.
  set_fact: php_packages={{ __php_packages | list }}
  when: php_packages is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- include: configure-RedHat.yml
  when: ansible_os_family == "RedHat"
