---
- name: define php_enablerepo
  set_fact: php_enablerepo={{ __php_enablerepo }}
  when: php_enablerepo is not defined

- name: install php packages
  yum: name={{ item }} state=present enablerepo={{ php_enablerepo }}
  with_items: php_packages
